using Norsevar.VFX;
using Sirenix.OdinInspector;
using UnityEngine;

namespace Norsevar
{
    public class NorseGameEventBindingsSO : ScriptableObject
    {

        #region Serialized Fields

        [SerializeField]
        [Title("THIS SO IS AUTOGENERATED, DON'T USE MANUALLY")]
        private NorseGameEventDictionary eventBindings;

        #endregion

        #region Public Methods

        public void Add(int norseGameEvent, NorseGameEvent norseEvent)
        {
            eventBindings.Add(norseGameEvent, norseEvent);
        }
        
        public void Remove(int id)
        {
            eventBindings.Remove(id);
        }

        public void Clear()
        {
            eventBindings.Clear();
        }

        #endregion

        public NorseGameEvent this[int id] => eventBindings[id];
    }
}
